FROM microsoft/dotnet:2.2.0-aspnetcore-runtime-alpine AS runtime

RUN apk add --no-cache --update \
    python \
    ffmpeg \
    libuv \
    curl \
    curl-dev && \
    curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && \
    chmod a+rx /usr/local/bin/youtube-dl && \
    youtube-dl -U

