FROM microsoft/dotnet:2.2.0-aspnetcore-runtime AS runtime

RUN apt-get update
RUN apt-get -y install \
    python \
    ffmpeg \
    curl && \
    curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && \
    chmod a+rx /usr/local/bin/youtube-dl && \
    youtube-dl -U

